"""Periodization models

Revision ID: 6d41b0c81973
Revises: b16aa0e80ecd
Create Date: 2021-08-31 15:55:56.972108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d41b0c81973'
down_revision = 'b16aa0e80ecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('span',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=True),
    sa.Column('start', sa.Date(), nullable=True),
    sa.Column('end', sa.Date(), nullable=True),
    sa.CheckConstraint('start>"end"', name='checkdates'),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('split',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('spans', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['spans'], ['span.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('splitgroup',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('splits', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['splits'], ['split.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('splitgroup')
    op.drop_table('split')
    op.drop_table('span')
    # ### end Alembic commands ###
